providers = ["python", "nodejs"]

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'npm install'
]

[phases.build]
cmds = [
    'python -c "from app import app, db; app.app_context().push(); db.create_all(); print(\"Database initialized\")"'
]
