[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.setuptools", "nodejs"]

[phases.install]
cmds = [
    "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python3 get-pip.py --break-system-packages",
    "python3 -m pip install -r requirements.txt --break-system-packages",
    "npm install"
]

[start]
cmd = "python3 -m gunicorn app:app --bind 0.0.0.0:$PORT"
