[providers]
python = "3.9"
nodejs = "18"

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'npm install'
]

[phases.build]
cmds = [
    'python -c "from app import app, db; app.app_context().push(); db.create_all(); print(\"Database initialized\")"'
]

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1'
